title: Low Wei Qing
#logo: 
description: I'm a robotics systems engineer with a passion for solving real-world problems using autonomous systems and project-based innovation. Experienced in integrating hardware/software with system-level thinking.
#show_downloads: true
theme: jekyll-theme-minimal
